// events.js — 고유 이벤트 50개 + 찌라시 RUMOR_EVENTS 15개
// 모든 이벤트 choices 3개 포함

const GENERAL_EVENTS = [
  // ── STUDY (12) ──────────────────────────────────────────
  {id:"gs1",title:"교수님이 갑자기 퀴즈를 공지했다",description:"수업 끝나자마자 단톡에 퀴즈 공지가 올라왔다.\n다들 한숨을 쉬었다. 대학생활은 늘 이런 식으로 갑자기 진지해진다.",category:"study",
   choices:[{text:"밤새 공부한다",effect:{gradePoint:7,stress:7,health:-3}},{text:"친구 필기를 급하게 빌린다",effect:{gradePoint:4,relationship:2,stress:3}},{text:"운에 맡긴다",effect:{gradePoint:"RANDOM_MEDIUM",stress:1}}]},
  {id:"gs2",title:"조별과제 팀원이 잠수를 탔다",description:"카톡을 읽고도 답이 없다. 기다리다 결국 혼자 하기로 마음먹었다.\n이런 경험이 사람을 성장시킨다는 말을 믿고 싶다.",category:"study",
   choices:[{text:"혼자 다 한다",effect:{gradePoint:6,stress:9,health:-2}},{text:"교수님께 사실대로 말한다",effect:{gradePoint:2,stress:4,relationship:-3}},{text:"팀원을 끝까지 설득한다",effect:{gradePoint:3,stress:5,relationship:4}}]},
  {id:"gs3",title:"발표 순서가 생각보다 빨리 왔다",description:"아직 준비가 덜 됐는데 이름이 불렸다. 심장이 세 배 빠르게 뛴다.",category:"study",
   choices:[{text:"끝까지 준비한 대로 간다",effect:{gradePoint:5,stress:7}},{text:"대충 버무려서 발표한다",effect:{gradePoint:1,stress:3}},{text:"다음 주로 미룬다고 한다",effect:{gradePoint:-2,stress:-2,relationship:-1}}]},
  {id:"gs4",title:"과제 마감이 겹쳤다",description:"A 과제 마감이 내일인데 B 과제도 내일이다.\n인생은 왜 언제나 몰아서 오는가.",category:"study",
   choices:[{text:"둘 다 밤새 완성한다",effect:{gradePoint:6,stress:10,health:-4}},{text:"중요한 것만 제대로 한다",effect:{gradePoint:3,stress:5}},{text:"교수님께 연장 요청한다",effect:{gradePoint:1,stress:2,relationship:-1}}]},
  {id:"gs5",title:"노트북이 과제 제출 30분 전에 멈췄다",description:"저장을 안 했을 수도 있다는 생각에 등에서 식은땀이 흘렀다.",category:"study",
   choices:[{text:"강제 재부팅 후 복구 시도",effect:{gradePoint:4,stress:9}},{text:"학교 컴퓨터실로 뛴다",effect:{gradePoint:5,stress:7,health:-2}},{text:"교수님께 상황을 설명한다",effect:{gradePoint:2,stress:4}},{text:"그냥 늦게 낸다",effect:{gradePoint:-3,stress:-1}}]},
  {id:"gs6",title:"수업이 생각보다 훨씬 어렵다",description:"강의계획서에는 분명 기초 과목이라고 적혀 있었다. 현실은 달랐다.",category:"study",
   choices:[{text:"열심히 따라간다",effect:{gradePoint:5,stress:6}},{text:"스터디 그룹을 만든다",effect:{gradePoint:3,relationship:4,stress:3}},{text:"수강 취소를 검토한다",effect:{stress:-3,career:-1}}]},
  {id:"gs7",title:"족보를 입수했다",description:"출처 불명의 파일이 단톡방을 타고 왔다. 믿어야 할지 말아야 할지.",category:"study",
   choices:[{text:"믿고 외운다",effect:{gradePoint:"RANDOM_MEDIUM",stress:-3}},{text:"참고용으로만 본다",effect:{gradePoint:3,stress:1}},{text:"쓰지 않는다",effect:{gradePoint:1,stress:0}}]},
  {id:"gs8",title:"도서관 자리 전쟁이 시작됐다",description:"시험 기간엔 자리 하나가 전략 자산이 된다.\n아침 7시에 이미 사람이 가득 차 있었다.",category:"study",
   choices:[{text:"새벽부터 자리를 잡는다",effect:{gradePoint:5,health:-2,stress:4}},{text:"카페로 간다",effect:{gradePoint:3,money:-4,stress:1}},{text:"집에서 공부한다",effect:{gradePoint:2,stress:-2,health:2}}]},
  {id:"gs9",title:"교수님이 갑작스럽게 수업 취소를 공지했다",description:"생겼다, 빈 시간이. 이걸 어떻게 쓰느냐가 오늘의 선택이다.",category:"study",
   choices:[{text:"밀린 공부를 한다",effect:{gradePoint:4,stress:3}},{text:"그냥 쉰다",effect:{stress:-6,health:4}},{text:"친구를 급하게 불러서 논다",effect:{relationship:5,money:-3,stress:-3}}]},
  {id:"gs10",title:"프린트 줄이 미쳤다",description:"시험 기간 도서관 프린터 앞에 줄이 복도까지 이어졌다.\n출력 한 장이 이렇게 전략적일 줄 몰랐다.",category:"study",
   choices:[{text:"줄을 기다린다",effect:{stress:4,gradePoint:2}},{text:"편의점 프린터를 쓴다",effect:{money:-2,stress:2,gradePoint:2}},{text:"핸드폰으로 대신 본다",effect:{stress:2,gradePoint:1}}]},
  {id:"gs11",title:"강의실 맨 앞자리에 앉게 됐다",description:"늦게 들어갔더니 뒤에 자리가 없다. 교수님 눈이 자꾸 마주친다.",category:"study",
   choices:[{text:"집중해서 듣는다",effect:{gradePoint:4,stress:2}},{text:"딴짓하다 들킨다",effect:{gradePoint:-2,stress:5,relationship:-1}},{text:"질문을 던져서 어필한다",effect:{gradePoint:3,relationship:2,stress:4}}]},
  {id:"gs12",title:"팀플 무임승차자가 발생했다",description:"4명이서 해야 할 일을 3명이 하고 있다. 그 한 명은 '바쁘다'고 한다.",category:"study",
   choices:[{text:"혼자 다 한다 (이번 한 번)",effect:{gradePoint:5,stress:8,relationship:-2}},{text:"단호하게 역할 분담을 요구한다",effect:{gradePoint:3,stress:5,relationship:3}},{text:"교수님께 보고한다",effect:{gradePoint:2,stress:3,relationship:-4}}]},

  // ── LIFE (10) ────────────────────────────────────────────
  {id:"gl1",title:"자취방 냉장고가 텅 비었다",description:"자취 생활의 낭만은 냉장고를 열어보는 순간 사라진다.\n오늘 뭘 먹을지가 진짜 문제다.",category:"life",
   choices:[{text:"장을 보러 간다",effect:{money:-5,health:3,stress:-2}},{text:"배달을 시킨다",effect:{money:-8,health:1,stress:-3}},{text:"라면으로 해결한다",effect:{money:-1,health:-2,stress:-1}}]},
  {id:"gl2",title:"몸살 기운이 있다",description:"목이 칼칼하고 머리가 무겁다. 오늘 9시 수업은 어떻게 할까.",category:"life",
   choices:[{text:"억지로 나간다",effect:{gradePoint:2,health:-4,stress:4}},{text:"하루 쉰다",effect:{health:7,stress:-5,gradePoint:-2}},{text:"약 먹고 버틴다",effect:{money:-2,health:2,stress:2}}]},
  {id:"gl3",title:"비 오는 날 우산이 없다",description:"아침에 맑았는데. 교문 앞에서 쏟아지는 비를 바라본다.",category:"life",
   choices:[{text:"그냥 맞고 간다",effect:{health:-3,stress:2}},{text:"편의점에서 우산을 산다",effect:{money:-4,stress:-1}},{text:"수업을 결석한다",effect:{gradePoint:-3,stress:-4,health:3}}]},
  {id:"gl4",title:"배달앱을 켰다가 멈췄다",description:"배달비 4500원. 최소 주문 1만 5천원. 혼자 먹기엔 너무 많다.",category:"life",
   choices:[{text:"그냥 시킨다",effect:{money:-9,stress:-4}},{text:"편의점으로 간다",effect:{money:-2,stress:1}},{text:"직접 해먹는다",effect:{money:-2,health:3,stress:-1}}]},
  {id:"gl5",title:"알람을 10개 맞췄는데도 불안하다",description:"내일 8시 수업. 알람을 10개 맞췄는데 자꾸 확인하게 된다.",category:"life",
   choices:[{text:"그냥 일찍 잔다",effect:{health:4,stress:-4}},{text:"유튜브 보다 늦게 잔다",effect:{health:-2,stress:2}},{text:"친구한테 깨워달라고 한다",effect:{relationship:2,stress:-3}}]},
  {id:"gl6",title:"생활비가 바닥나고 있다",description:"카드 앱을 열었다가 잔액을 보고 화면을 꺼버렸다.",category:"life",
   choices:[{text:"부모님께 용돈 요청한다",effect:{money:12,stress:3}},{text:"알바를 추가로 넣는다",effect:{money:10,stress:6,health:-2}},{text:"한 주 절약 모드 돌입",effect:{money:4,stress:2}}]},
  {id:"gl7",title:"방 청소를 너무 오래 미뤘다",description:"방이 고고학 발굴 현장이 됐다. 더 이상 미룰 수 없는 상태다.",category:"life",
   choices:[{text:"다 치운다",effect:{stress:-5,health:2}},{text:"보이는 것만 정리한다",effect:{stress:-2}},{text:"오늘도 못 본 척한다",effect:{stress:2,health:-1}}]},
  {id:"gl8",title:"학식이 오늘따라 애매했다",description:"3500원을 냈는데 이게 맞나 싶다. 배는 찼지만 마음이 허하다.",category:"life",
   choices:[{text:"그냥 먹는다",effect:{money:-3,health:1}},{text:"학식 후기를 올린다",effect:{stress:-2,relationship:2}},{text:"내일부터 도시락을 싸온다",effect:{money:3,health:2,stress:3}}]},
  {id:"gl9",title:"핸드폰을 강의실에 두고 왔다",description:"강의실 문이 이미 잠겨 있다. 분실 신고를 할지 내일까지 기다릴지.",category:"life",
   choices:[{text:"학과 사무실에 분실 신고",effect:{stress:3,relationship:1}},{text:"내일 일찍 찾으러 간다",effect:{stress:4,health:-1}},{text:"오늘 하루 폰 없이 산다",effect:{stress:-2,health:2}}]},
  {id:"gl10",title:"편의점에서 쓸데없는 걸 샀다",description:"2+1이라길래 샀는데 집에 이미 세 개가 있다.",category:"life",
   choices:[{text:"다음부터 안 산다(이번이 마지막)",effect:{stress:-2,money:-3}},{text:"친구한테 나눠준다",effect:{relationship:3,money:-2}},{text:"스트레스 해소라고 합리화한다",effect:{stress:-3,money:-3}}]},

  // ── CAREER (10) ──────────────────────────────────────────
  {id:"gc1",title:"취업 박람회 공지가 떴다",description:"막상 공고가 눈앞에 나타나면 갑자기 현실이 된다.",category:"career",
   choices:[{text:"이력서 챙겨서 간다",effect:{career:7,stress:5,money:-1}},{text:"구경만 간다",effect:{career:3,stress:2}},{text:"온라인으로 대충 본다",effect:{career:1,stress:1}}]},
  {id:"gc2",title:"링크드인을 깔았다가 현타가 왔다",description:"같은 나이인데 왜 저 사람은 인턴도 하고 논문도 있지.",category:"career",
   choices:[{text:"자극받아서 스펙 정리 시작",effect:{career:5,stress:5}},{text:"앱을 지워버린다",effect:{stress:-3}},{text:"그냥 더 본다(자학)",effect:{stress:8,career:1}}]},
  {id:"gc3",title:"면접 스터디 제안이 왔다",description:"같이 스터디하자는 연락이 왔다. 귀찮지만 혼자가 더 막막하다.",category:"career",
   choices:[{text:"합류한다",effect:{career:6,relationship:4,stress:4}},{text:"한 번만 가보고 결정한다",effect:{career:3,stress:2}},{text:"혼자 하겠다고 한다",effect:{career:2,stress:1}}]},
  {id:"gc4",title:"자소서를 6개월 만에 다시 열었다",description:"처음부터 다시 써야 할 것 같다. 그때의 나는 뭘 쓴 건지.",category:"career",
   choices:[{text:"오늘 밤 안에 끝낸다",effect:{career:8,stress:8,health:-1}},{text:"조금씩 고쳐 나간다",effect:{career:4,stress:3}},{text:"내일 하기로 한다",effect:{stress:2}}]},
  {id:"gc5",title:"선배가 인턴 공고를 카톡으로 보내줬다",description:"'이거 해봐, 너 잘할 것 같아.' 짧은 문장이 현실을 당겨온다.",category:"career",
   choices:[{text:"바로 지원한다",effect:{career:8,stress:6}},{text:"좀 더 준비하고 지원한다",effect:{career:5,stress:3}},{text:"이번엔 패스한다",effect:{stress:-1}}]},
  {id:"gc6",title:"공모전 팀원을 급하게 구해야 한다",description:"혼자는 못 나가고 팀은 없다. SNS에 모집 글을 올렸는데 반응이 없다.",category:"career",
   choices:[{text:"학과 단톡에 올린다",effect:{career:5,relationship:3,stress:3}},{text:"혼자 낼 수 있는 공모전으로 바꾼다",effect:{career:3,stress:2}},{text:"이번 공모전은 포기한다",effect:{stress:-2}}]},
  {id:"gc7",title:"교수님이 기업 연계 얘기를 꺼냈다",description:"수업 중 갑자기 실무 연계 기회 이야기가 나왔다. 기회인 것 같다.",category:"career",
   choices:[{text:"수업 끝나고 교수님께 물어본다",effect:{career:6,stress:3,relationship:3}},{text:"공지를 기다린다",effect:{career:2}},{text:"내 길은 내가 찾는다",effect:{career:1}}]},
  {id:"gc8",title:"스터디룸에서 취업 얘기만 나왔다",description:"공부하러 갔다가 불안만 얻어왔다. 비교는 동기부여가 되기도, 독이 되기도 한다.",category:"career",
   choices:[{text:"자극받아서 스펙을 찾아본다",effect:{career:4,stress:5}},{text:"흘려듣고 내 공부한다",effect:{gradePoint:3,stress:1}},{text:"분위기 환기시킨다",effect:{relationship:4,stress:-2}}]},
  {id:"gc9",title:"졸업 후 진로 고민이 갑자기 몰려왔다",description:"취업, 대학원, 창업. 선택지가 많을수록 머리가 아프다.",category:"career",
   choices:[{text:"진로 상담을 예약한다",effect:{career:4,stress:-2}},{text:"선배들한테 직접 물어본다",effect:{career:3,relationship:4,stress:3}},{text:"일단 당장 할 수 있는 걸 한다",effect:{career:5,stress:4}}]},
  {id:"gc10",title:"자격증 시험 접수 마감이 내일이다",description:"공부는 아직 시작도 못 했는데 접수 마감이 내일이다.",category:"career",
   choices:[{text:"일단 접수하고 본다",effect:{career:5,money:-4,stress:4}},{text:"이번 회차는 포기한다",effect:{stress:-1}},{text:"오늘 밤 벼락치기로 공부 시작",effect:{career:3,stress:7,health:-2}}]},

  // ── RELATIONSHIP (10) ────────────────────────────────────
  {id:"gr1",title:"과 단톡방이 불타고 있다",description:"무슨 일인지는 몰라도 읽씹하기 애매한 분위기가 됐다.",category:"relationship",
   choices:[{text:"참전한다",effect:{relationship:5,stress:4}},{text:"읽씹한다",effect:{relationship:-1,stress:-1}},{text:"알림을 끈다",effect:{stress:-3,relationship:-2}}]},
  {id:"gr2",title:"선배가 갑자기 밥을 사준다고 했다",description:"좋은 건지, 뭔가 부탁이 있는 건지. 일단 가보기로 했다.",category:"relationship",
   choices:[{text:"감사히 얻어먹는다",effect:{relationship:5,money:6}},{text:"내 것도 낸다",effect:{relationship:3,money:-4}},{text:"부담스러워서 거절한다",effect:{relationship:-2,stress:1}}]},
  {id:"gr3",title:"친구가 갑자기 서운하다고 했다",description:"별로 한 게 없는 것 같은데 서운하다는 연락이 왔다.",category:"relationship",
   choices:[{text:"솔직하게 대화한다",effect:{relationship:5,stress:3}},{text:"일단 사과한다",effect:{relationship:3,stress:2}},{text:"모른 척한다",effect:{relationship:-4,stress:-1}}]},
  {id:"gr4",title:"오랜만에 고등학교 친구한테서 연락이 왔다",description:"잠깐 그 시절이 떠올랐다. 자꾸 멀어지는 것 같았는데.",category:"relationship",
   choices:[{text:"만나기로 한다",effect:{relationship:6,stress:-4,money:-4}},{text:"카톡만 주고받는다",effect:{relationship:3,stress:-2}},{text:"나중에 답한다고 하고 잊는다",effect:{relationship:-1}}]},
  {id:"gr5",title:"어색한 술자리가 잡혔다",description:"별로 안 친한데 같이 가야 하는 자리. 분위기는 예측 불가다.",category:"relationship",
   choices:[{text:"분위기 메이커를 자처한다",effect:{relationship:7,stress:4,money:-3}},{text:"조용히 있는다",effect:{relationship:2,stress:1}},{text:"한두 시간 후 빠진다",effect:{relationship:-1,stress:-3}}]},
  {id:"gr6",title:"후배가 고민 상담을 요청했다",description:"나도 잘 모르는 게 많은데 선배로서 뭔가를 말해줘야 할 것 같다.",category:"relationship",
   choices:[{text:"진심으로 들어준다",effect:{relationship:5,stress:3}},{text:"경험을 솔직히 나눈다",effect:{relationship:4,stress:1}},{text:"바쁘다고 한다",effect:{relationship:-3,stress:-1}}]},
  {id:"gr7",title:"누가 누구 좋아한다는 소문이 돌았다",description:"학과 단톡이 갑자기 시끄러워졌다. 소문은 빠르고 학교는 좁다.",category:"relationship",
   choices:[{text:"적극적으로 리액션한다",effect:{relationship:5,love:2,stress:1}},{text:"흘려듣는다",effect:{relationship:1}},{text:"당사자한테 직접 물어본다",effect:{relationship:-2,love:3,stress:3}}]},
  {id:"gr8",title:"친구가 갑자기 창업을 했다고 했다",description:"같이 입학한 친구가 벌써 사업자등록을 냈다. 이상하게 자극이 된다.",category:"relationship",
   choices:[{text:"진심으로 응원한다",effect:{relationship:4,career:2,stress:2}},{text:"리스크를 걱정해준다",effect:{relationship:2,career:1}},{text:"같이 하자고 한다",effect:{relationship:5,career:4,stress:5,money:-3}}]},
  {id:"gr9",title:"동기랑 사소한 감정 싸움이 생겼다",description:"별거 아닌 일인데 묘하게 감정이 상했다. 먼저 말을 걸어야 할까.",category:"relationship",
   choices:[{text:"먼저 연락한다",effect:{relationship:4,stress:2}},{text:"시간이 해결해준다고 믿는다",effect:{relationship:-1,stress:1}},{text:"공통 친구한테 부탁한다",effect:{relationship:2,stress:3}}]},
  {id:"gr10",title:"교환학생 모집 공고가 떴다",description:"해외에서 한 학기를 보낼 수 있는 기회가 왔다. 설레지만 두렵다.",category:"relationship",
   choices:[{text:"지원한다",effect:{career:6,relationship:4,stress:5,money:-5}},{text:"더 알아보고 결정한다",effect:{career:2,stress:2}},{text:"다음 기회를 노린다",effect:{stress:-1}}]},

  // ── MONEY (8) ────────────────────────────────────────────
  {id:"gm1",title:"교통비가 생각보다 많이 나갔다",description:"카드 명세를 보다가 교통비 항목에서 멈췄다.",category:"money",
   choices:[{text:"걸어다니기로 한다",effect:{health:3,money:3,stress:1}},{text:"정기권을 끊는다",effect:{money:3,stress:-1}},{text:"카풀 친구를 구한다",effect:{relationship:3,money:3}}]},
  {id:"gm2",title:"알바 월급날이 됐다",description:"이 돈으로 뭘 할지 이미 머릿속에 목록이 있다.",category:"money",
   choices:[{text:"생활비로 아껴 쓴다",effect:{money:10,stress:1}},{text:"하고 싶었던 걸 산다",effect:{stress:-5,money:5}},{text:"전액 저금한다",effect:{money:12,stress:2}}]},
  {id:"gm3",title:"장학금 공지 메일이 왔다",description:"받을 수 있을지는 모르겠지만 일단 확인해본다.",category:"money",
   choices:[{text:"바로 서류를 준비한다",effect:{money:15,stress:4,gradePoint:1}},{text:"내일 하지 뭐",effect:{money:5,stress:1}},{text:"어차피 안 될 것 같아서 패스",effect:{stress:-1}}]},
  {id:"gm4",title:"계좌 잔액을 보고 잠깐 멈췄다",description:"앱을 열었다가 잔액을 보고 화면을 꺼버렸다.",category:"money",
   choices:[{text:"지출 내역을 분석한다",effect:{money:3,stress:3}},{text:"알바를 추가로 넣는다",effect:{money:8,stress:6,health:-1}},{text:"오늘만 모른 척한다",effect:{stress:-1}}]},
  {id:"gm5",title:"친구가 돈을 빌려달라고 했다",description:"급하다고 한다. 친구 사이에서 돈 문제는 늘 조심스럽다.",category:"money",
   choices:[{text:"빌려준다",effect:{relationship:4,money:-6}},{text:"부분만 빌려준다",effect:{relationship:2,money:-3}},{text:"지금 나도 없다고 한다",effect:{relationship:-2,stress:2}}]},
  {id:"gm6",title:"충동구매를 했다",description:"필요한 건 아닌데 눈에 들어와서 샀다. 지금 당장은 기분이 좋다.",category:"money",
   choices:[{text:"뭐 어때, 기분이 중요하지",effect:{stress:-4,money:-7}},{text:"후회하면서 그냥 쓴다",effect:{stress:1,money:-5}},{text:"환불하러 간다",effect:{money:5,stress:2}}]},
  {id:"gm7",title:"로또를 샀다",description:"1등 당첨금 20억. 이 번호만 나오면 모든 게 해결된다는 상상을 1초 했다.",category:"money",
   choices:[{text:"진지하게 번호를 고른다",effect:{money:-2,stress:-3}},{text:"자동으로 산다",effect:{money:-2,stress:-2}},{text:"사면서 이미 당첨된 상상을 한다",effect:{stress:-5,money:-2}}]},
  {id:"gm8",title:"중고거래를 시도했다",description:"안 쓰는 물건을 팔려고 올렸다. 네고 요청이 세 개 왔다.",category:"money",
   choices:[{text:"정가 고수한다",effect:{money:6,stress:2}},{text:"적당히 네고해준다",effect:{money:4,relationship:1}},{text:"그냥 버린다",effect:{stress:-2}}]}
];

// ── 찌라시 이벤트 (RUMOR_EVENTS) ──────────────────────────
const RUMOR_EVENTS = [
  {id:"r1",title:"릴스에서 '봄동비빔밥' 레시피를 봤다",description:"생각보다 진지하게 맛있어 보여서 저장까지 눌렀다.\n스크롤 하다 생긴 식욕이 오늘 기분을 바꿔놨다.",category:"rumor",effect:{stress:-10,otaku:1}},
  {id:"r2",title:"쇼츠에서 '나무 챌린지'가 자꾸 뜬다",description:"처음엔 어이없었는데 보고 있자니 은근 중독된다.\n10분째 보고 있다는 걸 방금 깨달았다.",category:"rumor",effect:{stress:-6,otaku:1}},
  {id:"r3",title:"'동결건조' 밈이 타임라인을 뒤덮었다",description:"사람들이 진심과 농담을 이상하게 잘 섞어 쓰고 있었다.\n두 번 읽으니 웃겼고 세 번 읽으니 공감됐다.",category:"rumor",effect:{stress:-4,relationship:1}},
  {id:"r4",title:"교내 커플 목격담이 익명 게시판에 올라왔다",description:"아는 사람인 것 같기도 하고 아닌 것 같기도 하다.\n댓글이 벌써 80개다.",category:"rumor",effect:{stress:-3,love:2}},
  {id:"r5",title:"학식 신메뉴가 극호불호를 갈랐다",description:"단톡에서 학식 얘기로 30분이 날아갔다.\n이 에너지를 공부에 쓰면 전교 1등이다.",category:"rumor",effect:{stress:-4,relationship:2}},
  {id:"r6",title:"족보가 돌고 있다는 소문이 났다",description:"출처불명의 파일이 단톡방을 타고 왔다.\n맞는 건지 확인할 방법은 없지만 다들 저장했다.",category:"rumor",effect:{stress:-5,gradePoint:2}},
  {id:"r7",title:"MT 장소가 공식 발표 전에 유출됐다",description:"아직 공식 발표도 안 됐는데 다들 알고 있다.\n이 학교에서 비밀은 24시간이 한계다.",category:"rumor",effect:{stress:-3,relationship:3}},
  {id:"r8",title:"어떤 교수님이 수업 중에 우셨다는 얘기가 돈다",description:"왜 우셨는지에 대한 해석이 버전이 세 개다.\n학교는 생각보다 감정적인 공간이기도 하다.",category:"rumor",effect:{stress:-2,relationship:3}},
  {id:"r9",title:"요즘 유행하는 MBTI 테스트가 또 바뀌었다",description:"이번엔 16개가 아니라 32개라는 게 특징이다.\n근거가 없어도 사람들은 열심히 한다.",category:"rumor",effect:{stress:-5,relationship:2}},
  {id:"r10",title:"아이돌 내한 콘서트 공지가 떴다",description:"티켓팅 날짜가 중간고사 기간과 딱 겹친다.\n이 타이밍은 우연인지 의도인지.",category:"rumor",effect:{stress:-8,otaku:3,money:-2}},
  {id:"r11",title:"누군가 도서관에서 수상한 행동을 했다는 글이 올라왔다",description:"구체적인 내용은 없는데 댓글이 넘친다.\n익명 게시판은 오늘도 활발하다.",category:"rumor",effect:{stress:-2,relationship:2}},
  {id:"r12",title:"학교 앱이 갑자기 서버 다운됐다",description:"수강신청도 성적 확인도 다 안 된다.\n단톡방 전체가 패닉 상태다.",category:"rumor",effect:{stress:5,gradePoint:-1}},
  {id:"r13",title:"편의점 인기 신상이 품절됐다",description:"2+1 행사 첫날부터 동났다. 사재기 의혹까지 나왔다.",category:"rumor",effect:{stress:-3,money:-1}},
  {id:"r14",title:"과 선배가 외국계 대기업에 입사했다는 소식이 돌았다",description:"진짜인지 과장인지는 모르겠지만 단톡이 술렁이고 있다.\n자극인지 압박인지 모를 감정이 온다.",category:"rumor",effect:{stress:3,career:3}},
  {id:"r15",title:"학교 근처 맛집이 갑자기 미슐랭을 받았다는 소문이 났다",description:"가봤던 곳인데 갑자기 줄이 생겼다.\n아는 맛인데 다르게 느껴지는 게 이상하다.",category:"rumor",effect:{stress:-4,money:-2,relationship:1}}
];
